name = "CircularList"
uuid = "e1d4a2be-69cc-597c-a2ea-cc5d6f241fff"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "1.2.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
